2022-12-21 10:49:14,968 fflow.py initialize [line:255] INFO Using Logger in `utils.logger.basic_logger`
2022-12-21 10:49:14,969 fflow.py initialize [line:256] INFO Initializing fedtask: pill_classification
2022-12-21 10:49:15,029 fflow.py initialize [line:272] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2022-12-21 10:49:15,030 fflow.py initialize [line:298] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/aiotlabws/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 10:49:21,331 fflow.py initialize [line:318] INFO Initializing Clients: 10 clients of `algorithm.fedalgo2.Client` being created.
2022-12-21 10:49:21,333 fflow.py initialize [line:339] INFO Initializing Server: 1 server of `algorithm.fedalgo2.Server` being created.
2022-12-21 10:49:21,334 fflow.py initialize [line:352] INFO Ready to start.
2022-12-21 10:49:21,334 fedbase.py run [line:61] INFO --------------Round 1--------------
2022-12-21 10:49:25,320 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.0130
2022-12-21 10:49:25,321 basic_logger.py show_current_output [line:134] INFO test_loss                     4.5173
2022-12-21 10:49:25,321 basic_logger.py time_end [line:74] INFO Eval Time Cost:               3.9865s
2022-12-21 10:49:25,322 fedalgo2.py iterate [line:22] INFO Selected clients : [1, 2]
Using cache found in /home/aiotlabws/.cache/torch/hub/pytorch_vision_v0.10.0
Total samples which participate training : 1495 samples
> /mnt/disk2/ndlong/easyFL/algorithm/fedbase.py(84)run()
-> utils.fmodule.save_json(self.log_file, f'{self.option["log_result_path"]}/{self.option["group_name"]}',self.option["session_name"])
2022-12-21 10:52:56,996 basic_logger.py time_end [line:74] INFO Time Cost:                    215.6616s
2022-12-21 10:52:56,997 fedbase.py run [line:84] INFO --------------Round 2--------------
2022-12-21 10:52:59,884 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.2701
2022-12-21 10:52:59,885 basic_logger.py show_current_output [line:134] INFO test_loss                     3.3426
2022-12-21 10:52:59,885 basic_logger.py time_end [line:74] INFO Eval Time Cost:               2.8881s
2022-12-21 10:52:59,886 fedalgo2.py iterate [line:22] INFO Selected clients : [3, 0]
Using cache found in /home/aiotlabws/.cache/torch/hub/pytorch_vision_v0.10.0
Total samples which participate training : 1090 samples
> /mnt/disk2/ndlong/easyFL/algorithm/fedbase.py(83)run()
-> breakpoint()
2022-12-21 11:09:22,151 basic_logger.py time_end [line:74] INFO Time Cost:                    985.1544s
2022-12-21 11:09:22,152 fedbase.py run [line:83] INFO --------------Round 3--------------
2022-12-21 11:09:26,225 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.2805
2022-12-21 11:09:26,226 basic_logger.py show_current_output [line:134] INFO test_loss                     3.2596
2022-12-21 11:09:26,226 basic_logger.py time_end [line:74] INFO Eval Time Cost:               4.0737s
2022-12-21 11:09:26,227 fedalgo2.py iterate [line:22] INFO Selected clients : [1, 2]
Program interrupted. (Use 'cont' to resume).
> /mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/ImageFile.py(258)load()
-> if n < 0:
--KeyboardInterrupt--
--KeyboardInterrupt--
--KeyboardInterrupt--
2022-12-21 11:43:44,107 main.py main [line:24] ERROR Exception Logged
Traceback (most recent call last):
  File "main.py", line 24, in main
    server.run()
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedbase.py", line 83, in run
    flw.logger.info("--------------Final Evaluation--------------")
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 25, in iterate
    n_samples = received_information["n_samples"]
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 106, in communicate
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 85, in communicate_with
    def pack_model_threshold(self, client_id):
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 195, in reply
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedbase.py", line 424, in train
    outputs = model(data)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/disk2/ndlong/easyFL/benchmark/toolkits.py", line 1086, in __getitem__
    self.dataset[self.idxs[item]][0],
  File "/mnt/disk2/ndlong/easyFL/benchmark/toolkits.py", line 1086, in __getitem__
    self.dataset[self.idxs[item]][0],
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 232, in __getitem__
    sample = self.loader(path)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 269, in default_loader
    return pil_loader(path)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 251, in pil_loader
    return img.convert('RGB')
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/Image.py", line 934, in convert
    self.load()
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/ImageFile.py", line 258, in load
    if n < 0:
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/ImageFile.py", line 258, in load
    if n < 0:
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
Traceback (most recent call last):
  File "main.py", line 24, in main
    server.run()
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedbase.py", line 83, in run
    flw.logger.info("--------------Final Evaluation--------------")
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 25, in iterate
    n_samples = received_information["n_samples"]
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 106, in communicate
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 85, in communicate_with
    def pack_model_threshold(self, client_id):
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo2.py", line 195, in reply
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedbase.py", line 424, in train
    outputs = model(data)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/disk2/ndlong/easyFL/benchmark/toolkits.py", line 1086, in __getitem__
    self.dataset[self.idxs[item]][0],
  File "/mnt/disk2/ndlong/easyFL/benchmark/toolkits.py", line 1086, in __getitem__
    self.dataset[self.idxs[item]][0],
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 232, in __getitem__
    sample = self.loader(path)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 269, in default_loader
    return pil_loader(path)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 251, in pil_loader
    return img.convert('RGB')
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/Image.py", line 934, in convert
    self.load()
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/ImageFile.py", line 258, in load
    if n < 0:
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/site-packages/PIL/ImageFile.py", line 258, in load
    if n < 0:
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 24, in main
    server.run()
RuntimeError