wandb: Currently logged in as: longnd (aiotlab). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/wandb/run-20230109_043239-1xltc5ta
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fedalgo7_ratio_1.0_C_0.3_config2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/aiotlab/Abnormal_Data_FL
wandb: üöÄ View run at https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/1xltc5ta
2023-01-09 04:32:40,555 fflow.py initialize [line:267] INFO Using Logger in `utils.logger.basic_logger`
2023-01-09 04:32:40,555 fflow.py initialize [line:268] INFO Initializing fedtask: pill_classification
2023-01-09 04:32:40,809 fflow.py initialize [line:284] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2023-01-09 04:32:40,811 fflow.py initialize [line:312] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2023-01-09 04:32:45,363 fflow.py initialize [line:332] INFO Initializing Clients: 10 clients of `algorithm.fedalgo7.Client` being created.
2023-01-09 04:32:45,365 fflow.py initialize [line:353] INFO Initializing Server: 1 server of `algorithm.fedalgo7.Server` being created.
2023-01-09 04:32:45,376 fflow.py initialize [line:366] INFO Ready to start.
2023-01-09 04:32:45,376 fedbase.py run [line:63] INFO --------------Round 1--------------
2023-01-09 04:32:50,375 basic_logger.py show_current_output [line:147] INFO test_accuracy                 0.0130
2023-01-09 04:32:50,376 basic_logger.py show_current_output [line:147] INFO test_loss                     4.5173
2023-01-09 04:32:50,376 basic_logger.py time_end [line:77] INFO Eval Time Cost:               4.9999s
2023-01-09 04:32:50,382 fedalgo7.py iterate [line:111] INFO Selected clients : [1, 2, 7]
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2023-01-09 04:35:25,390 basic_logger.py time_end [line:77] INFO Time Cost:                    160.0141s
2023-01-09 04:35:25,391 fedbase.py run [line:63] INFO --------------Round 2--------------
2023-01-09 04:35:28,127 basic_logger.py show_current_output [line:147] INFO test_accuracy                 0.0584
2023-01-09 04:35:28,127 basic_logger.py show_current_output [line:147] INFO test_loss                     4.1255
2023-01-09 04:35:28,127 basic_logger.py time_end [line:77] INFO Eval Time Cost:               2.7364s
2023-01-09 04:35:28,136 fedalgo7.py iterate [line:111] INFO Selected clients : [3, 0, 2]
2023-01-09 04:36:14,287 main.py main [line:27] ERROR Exception Logged
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 76, in run
    self.iterate()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo7.py", line 113, in iterate
    aggregated_histogram = self.communicate_score(self.selected_clients)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo7.py", line 249, in communicate_score
    "history_cached": self.check_nearly_participated(),
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo7.py", line 137, in check_nearly_participated
    cared_round = self.option["fuzzy_config"]["history_sampled"]["n_rounds"]
KeyError: 'n_rounds'
Total samples which participate training : 2100/2100 samples
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 76, in run
    self.iterate()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo7.py", line 113, in iterate
    aggregated_histogram = self.communicate_score(self.selected_clients)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo7.py", line 249, in communicate_score
    "history_cached": self.check_nearly_participated(),
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo7.py", line 137, in check_nearly_participated
    cared_round = self.option["fuzzy_config"]["history_sampled"]["n_rounds"]
KeyError: 'n_rounds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 33, in <module>
    main()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 28, in main
    raise RuntimeError
RuntimeError
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: - 0.010 MB of 0.010 MB uploaded (0.000 MB deduped)wandb: \ 0.010 MB of 0.019 MB uploaded (0.000 MB deduped)wandb: | 0.019 MB of 0.019 MB uploaded (0.000 MB deduped)wandb: 
wandb: Run history:
wandb: Accuracy/Testing Accuracy ‚ñÅ‚ñà
wandb:         Loss/Testing Loss ‚ñà‚ñÅ
wandb: 
wandb: Run summary:
wandb: Accuracy/Testing Accuracy 0.05844
wandb:         Loss/Testing Loss 4.12551
wandb: 
wandb: Synced fedalgo7_ratio_1.0_C_0.3_config2: https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/1xltc5ta
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230109_043239-1xltc5ta/logs
