wandb: Currently logged in as: longnd (aiotlab). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.11 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/wandb/run-20230313_014343-1xlfhd05
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run algorithm/fedavg_v1_loss_based.py_ratio_1.0_C_0.3_baseline_loss
wandb: ⭐️ View project at https://wandb.ai/aiotlab/Abnormal_Data_FL
wandb: 🚀 View run at https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/1xlfhd05
2023-03-13 01:43:43,858 fflow.py initialize [line:270] INFO Using Logger in `utils.logger.basic_logger`
2023-03-13 01:43:43,859 fflow.py initialize [line:271] INFO Initializing fedtask: cifar10_classification
2023-03-13 01:43:45,521 fflow.py initialize [line:287] INFO Using model `resnet18` in `benchmark.cifar10_classification.model.resnet18` as the globally shared model.
2023-03-13 01:43:45,527 fflow.py initialize [line:315] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
2023-03-13 01:43:51,949 fflow.py initialize [line:339] INFO Initializing Clients: 100 clients of `algorithm.algorithm/fedavg_v1_loss_based.py.Client` being created.
>>>>>> Using cifar10 dataset
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 33, in <module>
    main()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 21, in main
    server = flw.initialize(option)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/utils/fflow.py", line 345, in initialize
    Client = getattr(importlib.import_module(client_path), "Client")
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'algorithm.algorithm/fedavg_v1_loss_based'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Synced algorithm/fedavg_v1_loss_based.py_ratio_1.0_C_0.3_baseline_loss: https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/1xlfhd05
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230313_014343-1xlfhd05/logs
