wandb: Currently logged in as: longnd (aiotlab). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.10 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/wandb/run-20230304_043340-6r28yqoe
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fedavg_ratio_1.0_C_0.3_blurry_0.5_100_5
wandb: ‚≠êÔ∏è View project at https://wandb.ai/aiotlab/Abnormal_Data_FL
wandb: üöÄ View run at https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/6r28yqoe
2023-03-04 04:33:41,540 fflow.py initialize [line:270] INFO Using Logger in `utils.logger.basic_logger`
2023-03-04 04:33:41,540 fflow.py initialize [line:271] INFO Initializing fedtask: cifar10_classification
2023-03-04 04:33:43,312 fflow.py initialize [line:287] INFO Using model `resnet18` in `benchmark.cifar10_classification.model.resnet18` as the globally shared model.
2023-03-04 04:33:43,318 fflow.py initialize [line:315] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
2023-03-04 04:33:47,441 fflow.py initialize [line:338] INFO Initializing Clients: 100 clients of `algorithm.fedavg.Client` being created.
2023-03-04 04:33:47,444 fflow.py initialize [line:359] INFO Initializing Server: 1 server of `algorithm.fedavg.Server` being created.
2023-03-04 04:33:47,445 fflow.py initialize [line:372] INFO Ready to start.
2023-03-04 04:33:47,445 fedbase.py run [line:64] INFO --------------Round 1--------------
2023-03-04 04:33:55,823 basic_logger.py show_current_output [line:148] INFO test_accuracy                 0.0939
2023-03-04 04:33:55,824 basic_logger.py show_current_output [line:148] INFO test_loss                     2.3042
2023-03-04 04:33:55,824 basic_logger.py time_end [line:78] INFO Eval Time Cost:               8.3786s
2023-03-04 04:33:55,828 fedbase.py iterate [line:119] INFO Selected clients : [23, 81, 85, 34, 62, 46, 42, 31, 93, 11, 22, 77, 66, 13, 10, 68, 27, 36, 86, 40, 19, 1, 3, 16, 17, 29, 49, 45, 58, 37]
>>>>>> Using cifar10 dataset
Files already downloaded and verified
Client 1 init its dataloader
> /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py(444)train()
-> torch.nn.CrossEntropyLoss(reduction="none")(outputs, labels)
(Pdb) 2023-03-04 04:33:55,912 main.py main [line:27] ERROR Exception Logged
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 77, in run
    self.iterate()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 123, in iterate
    models = self.communicate(self.selected_clients)["model"]
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 143, in communicate
    response_from_client_id = self.communicate_with(client_id)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 167, in communicate_with
    return self.clients[client_id].reply(svr_pkg)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 499, in reply
    self.train(model)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 444, in train
    torch.nn.CrossEntropyLoss(reduction="none")(outputs, labels)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 444, in train
    torch.nn.CrossEntropyLoss(reduction="none")(outputs, labels)
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 77, in run
    self.iterate()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 123, in iterate
    models = self.communicate(self.selected_clients)["model"]
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 143, in communicate
    response_from_client_id = self.communicate_with(client_id)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 167, in communicate_with
    return self.clients[client_id].reply(svr_pkg)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 499, in reply
    self.train(model)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 444, in train
    torch.nn.CrossEntropyLoss(reduction="none")(outputs, labels)
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 444, in train
    torch.nn.CrossEntropyLoss(reduction="none")(outputs, labels)
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 33, in <module>
    main()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 28, in main
    raise RuntimeError
RuntimeError
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb: Accuracy/Testing Accuracy ‚ñÅ
wandb:         Loss/Testing Loss ‚ñÅ
wandb: 
wandb: Run summary:
wandb: Accuracy/Testing Accuracy 0.0939
wandb:         Loss/Testing Loss 2.30424
wandb: 
wandb: Synced fedavg_ratio_1.0_C_0.3_blurry_0.5_100_5: https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/6r28yqoe
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230304_043340-6r28yqoe/logs
