wandb: Currently logged in as: longnd (aiotlab). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/wandb/run-20230104_033026-2qwm6j9d
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fedalgo6_dev_ratio_0.9_C_0.5_fixbug
wandb: ‚≠êÔ∏è View project at https://wandb.ai/aiotlab/Abnormal_Data_FL
wandb: üöÄ View run at https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/2qwm6j9d
2023-01-04 03:30:28,037 fflow.py initialize [line:262] INFO Using Logger in `utils.logger.basic_logger`
2023-01-04 03:30:28,037 fflow.py initialize [line:263] INFO Initializing fedtask: pill_classification
2023-01-04 03:30:28,449 fflow.py initialize [line:279] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2023-01-04 03:30:28,454 fflow.py initialize [line:307] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2023-01-04 03:30:34,577 fflow.py initialize [line:327] INFO Initializing Clients: 10 clients of `algorithm.fedalgo6_dev.Client` being created.
2023-01-04 03:30:34,578 fflow.py initialize [line:348] INFO Initializing Server: 1 server of `algorithm.fedalgo6_dev.Server` being created.
2023-01-04 03:30:34,578 fflow.py initialize [line:361] INFO Ready to start.
2023-01-04 03:30:34,578 fedbase.py run [line:62] INFO --------------Round 1--------------
2023-01-04 03:30:39,884 basic_logger.py show_current_output [line:147] INFO test_accuracy                 0.0130
2023-01-04 03:30:39,885 basic_logger.py show_current_output [line:147] INFO test_loss                     4.5173
2023-01-04 03:30:39,885 basic_logger.py time_end [line:77] INFO Eval Time Cost:               5.3068s
2023-01-04 03:30:39,889 fedalgo6_dev.py iterate [line:73] INFO Selected clients : [1, 2, 7, 3, 5]
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2023-01-04 03:33:56,908 basic_logger.py time_end [line:77] INFO Time Cost:                    202.3300s
2023-01-04 03:33:56,908 fedbase.py run [line:62] INFO --------------Round 2--------------
2023-01-04 03:34:01,916 basic_logger.py show_current_output [line:147] INFO test_accuracy                 0.1662
2023-01-04 03:34:01,918 basic_logger.py show_current_output [line:147] INFO test_loss                     3.9290
2023-01-04 03:34:01,919 basic_logger.py time_end [line:77] INFO Eval Time Cost:               5.0100s
2023-01-04 03:34:01,925 fedalgo6_dev.py iterate [line:73] INFO Selected clients : [3, 0, 2, 7, 9]
Number samples of this round:  [760, 760, 380, 600, 580]
Total samples which participate training : 3080/3080 samples
Update ratio round 2: 0.9 >>>>  0.7022712968183062
> /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/sampler/threshold_sampler.py(52)cal_threshold()
-> list_n_ , value_list = histogram
(Pdb) 2023-01-04 03:35:02,069 main.py main [line:27] ERROR Exception Logged
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 75, in run
    self.iterate()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo6_dev.py", line 78, in iterate
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo6_dev.py", line 65, in cal_threshold
    aggregated_histogram
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/sampler/threshold_sampler.py", line 52, in cal_threshold
    list_n_ , value_list = histogram
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/sampler/threshold_sampler.py", line 52, in cal_threshold
    list_n_ , value_list = histogram
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedbase.py", line 75, in run
    self.iterate()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo6_dev.py", line 78, in iterate
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/algorithm/fedalgo6_dev.py", line 65, in cal_threshold
    aggregated_histogram
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/sampler/threshold_sampler.py", line 52, in cal_threshold
    list_n_ , value_list = histogram
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/sampler/threshold_sampler.py", line 52, in cal_threshold
    list_n_ , value_list = histogram
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/apps/centos7/python/3.10.4_gcc11.2.0/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 33, in <module>
    main()
  File "/home/ace15032jo/Projects/repo2/SampleSelection_easyFL/main.py", line 28, in main
    raise RuntimeError
RuntimeError
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: - 0.019 MB of 0.019 MB uploaded (0.000 MB deduped)wandb: 
wandb: Run history:
wandb: Accuracy/Testing Accuracy ‚ñÅ‚ñà
wandb:         Loss/Testing Loss ‚ñà‚ñÅ
wandb:        mean_training_loss ‚ñÅ
wandb: 
wandb: Run summary:
wandb: Accuracy/Testing Accuracy 0.16623
wandb:         Loss/Testing Loss 3.92904
wandb:        mean_training_loss 0.91983
wandb: 
wandb: Synced fedalgo6_dev_ratio_0.9_C_0.5_fixbug: https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/2qwm6j9d
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230104_033026-2qwm6j9d/logs
